---
- name: Update APT Packager Manager repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade installed packages
  become: true
  ansible.builtin.apt:
    upgrade: dist

- name: Ping
  ansible.builtin.ping: ~

- name: Install low-level utilities
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - zip
    - unzip
