---
- name: "Ensure the ownership of {{ ansistrano_deploy_to }}"
  become: true
  ansible.builtin.file:
    path: "{{ ansistrano_deploy_to }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory
  tags:
    - permissions
    - deploy
