---
- name: Create project directory and sets permissions
  become: true
  file:
    path: "{{ project_root_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes