---
- name: Debug ansistrano_release_version
  ansible.builtin.debug:
    var: ansistrano_release_version
  tags:
    - deploy

- name: Installer composer dependencies
  community.general.composer:
    working_dir: "{{ '/var/www/project/current' }}"
    no_dev: "{{ 'yes' if ('prod' == symfony_env) else 'no' }}"
  environment:
    SYMFONY_ENV: "{{ symfony_env }}"
  tags:
    - deploy
    - composer

- name: Set Symfony secret in parameters.yml
  ansible.builtin.lineinfile:
    dest: "{{ symfony_root_dir }}/app/config/parameters.yml"
    regexp: "^    secret:"
    line: "    secret: {{ symfony_secret }}"
  tags:
    - deploy

- name: Set Loggly token in parameters.yml
  ansible.builtin.lineinfile:
    dest: "{{ symfony_root_dir }}/app/config/parameters.yml"
    regexp: "^    loggly_token:"
    line: "    loggly_token: {{ loggly_token }}"
  tags:
    - deploy

# Symfony commands

- name: Create DB if not exists
  ansible.builtin.command: "{{ symfony_console_path }} doctrine:database:create --if-not-exists"
  register: db_create_result
  changed_when: "not {{ db_create_result.stdout | search('already exists. Skipped') }}"
  environment:
    SYMFONY_ENV: "{{ symfony_env }}"
  tags:
    - deploy

- name: Executes migrations
  ansible.builtin.command: "{{ symfony_console_path }} doctrine:migrations:migrate --no-interaction"
  register: db_migrations_result
  changed_when: "not {{ db_migrations_result.stdout | search('No migrations to execute') }}"
  environment:
    SYMFONY_ENV: "{{ symfony_env }}"
  tags:
    - deploy

- name: Load data fixtures
  ansible.builtin.command: "{{ symfony_console_path }} hautelook_alice:doctrine:fixtures:load --no-interaction"
  environment:
    SYMFONY_ENV: "{{ symfony_env }}"
  changed_when: false
  when: symfony_env != "prod"
  tags:
    - deploy

- name: Clear cache
  ansible.builtin.command: "{{ ansistrano_release_path.stdout }}/bin/console cache:clear --env={{ symfony_env }}"
  environment:
    SYMFONY_ENV: "{{ symfony_env }}"
  changed_when: false
  tags:
    - deploy

- name: "Ensure the ownership (www-data) of var directory at {{ ansistrano_release_path.stdout }}"
  become: true
  ansible.builtin.file:
    path: "{{ ansistrano_release_path.stdout }}/var"
    owner: www-data
    group: www-data
    recurse: true
    state: directory
  tags:
    - permissions
    - deploy
